# Generated by Django 2.2.2 on 2022-08-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_store', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
